print("")
print("Cabinet is locked.")
print("Would you like to change the priorities of actions?")
print("")
print("A - Try Unlocking Cabinet again")
print("B – Wait 10 seconds")
print("C – Call supervisor for remote unlock")
print("")
print("Which action should I take first? (type A, B, or C)  _")
print("Which action should I take second? (type A, B, or C)  _")
print("")
print("")